### PR TITLE
Update ggcat

### PR DESCRIPTION
**Pull request by imartayan**
GGCAT needs to be updated, the current version of the submodule does not compile due to a nightly feature (`slice_group_by`) that was changed and stabilized in Rust 1.77.

### CODE REVIEW

**Comment by rob-p** [comment]
But 1.77 isn't released yet. Does ggcat build under stable rust? Is this PR to allow that - would be awesome :).

**Comment by imartayan** [comment]
The version currently used in the repository does not build under stable rust, and it does not build with the latest nightly version either because of the feature I mentioned. On the other hand, the latest version of ggcat (used in this PR) can be built with stable rust :)

**Comment by jermp** [comment]
Thanks Igor. So, can I merge the PR?
I did not see any problem in building with rust 1.69.0 but didn't try with 1.77.

**Comment by imartayan** [comment]
Yes, if you'd like to try it on your machine first you can pull the latest version of ggcat with `git submodule update --recursive --remote`.

**Comment by jermp** [comment]
On my machine it fails because of the matchtigs dependency:

    error: package `matchtigs v2.1.6` cannot be built because it requires rustc 1.70.0 or newer, while the currently active rustc version is 1.69.0

**Comment by rob-p** [comment]
@jermp probably you should do the build with 1.76 (which is the just released stable), but this is a huge win now having GGCAT build outside of nightly (and not use any features that might later be removed).

**Comment by jermp** [comment]
Yes, in fact I'm updating to rust 1.76.
I'll then merge this PR and update the README (where we still recommend to install nightly rust).

**Comment by jermp** [comment]
Alright, merged! Thanks Igor and Rob for the discussion.

**Pull request merged**
